config/routes.rb
DispatchServer::Application.routes.draw do
  resources :units

  root :to => 'units#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  def as_json(options={})
    super(:only => [:shop_nbr, :unit_nbr])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.json
  def index
    unit_nbr = params[:unit_nbr]
    if unit_nbr
      @units = Unit.where("unit_nbr=?",unit_nbr)
    else
      @units = Unit.all
    end
      render json: @units
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dispatch Server</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit_nbr %><br />
    <%= f.text_field :unit_nbr %>
  </div>
  <div class="field">
    <%= f.label :shop_nbr %><br />
    <%= f.text_field :shop_nbr %>
  </div>
  <div class="field">
    <%= f.label :home_station %><br />
    <%= f.number_field :home_station %>
  </div>
  <div class="field">
    <%= f.label :license %><br />
    <%= f.text_field :license %>
  </div>
  <div class="field">
    <%= f.label :radioid %><br />
    <%= f.text_field :radioid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Unit nbr</th>
    <th>Shop nbr</th>
    <th>Home station</th>
    <th>License</th>
    <th>Radioid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.unit_nbr %></td>
    <td><%= unit.shop_nbr %></td>
    <td><%= unit.home_station %></td>
    <td><%= unit.license %></td>
    <td><%= unit.radioid %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unit nbr:</b>
  <%= @unit.unit_nbr %>
</p>

<p>
  <b>Shop nbr:</b>
  <%= @unit.shop_nbr %>
</p>

<p>
  <b>Home station:</b>
  <%= @unit.home_station %>
</p>

<p>
  <b>License:</b>
  <%= @unit.license %>
</p>

<p>
  <b>Radioid:</b>
  <%= @unit.radioid %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>